openapi: 3.2.0
info:
  title: Sign In Solutions VMS Hosts API
  version: 0.21.0
  x-logo:
    url: https://signinenterprise.com/wp-content/uploads/tg-logo-light@2.png
    backgroundColor: '#FFFFFF'
    altText: Sign In Solutions
    href: https://signinsolutions.com/signinenterprise
  description: The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.
  contact:
    name: API Support
    url: https://signinsolutions.com/signinenterprise
    email: support@tractionguest.com
servers:
- url: '{domain}'
  variables:
    domain:
      enum:
      - https://us.tractionguest.com/api/v3
      - http://localhost:3000/api/v3
      default: https://us.tractionguest.com/api/v3
security:
- TractionGuestAuth:
  - all
  - openid
  - admin:webhooks
  - watchlists:*
  - watchlists:read
  - watchlists:write
  - users:*
  - users:read
  - users:write
  - visitors:*
  - visitors:read
  - visitors:write
  - parking:*
  - parking:read
  - parking:write
  - locations:*
  - locations:read
  - locations:write
  - hosts:*
  - hosts:read
  - hosts:write
  - email_templates:*
  - email_templates:read
  - email_templates:write
tags:
- name: Hosts
  description: All endpoints relating to the Host model
paths:
  /hosts:
    summary: Path used to manage the list of Hosts.
    description: The REST endpoint/path used to list and create zero or more `Host` entities.  This path contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
    get:
      tags:
      - Hosts
      parameters:
      - name: query
        description: Will filter by `first_name`, `last_name`, and `email`
        schema:
          type: string
        in: query
      - name: limit
        description: Limits the results to a specified number, defaults to 50
        schema:
          type: integer
        in: query
      - name: offset
        description: Offsets the results to a specified number, defaults to 0
        schema:
          type: integer
        in: query
      - name: include
        description: A list of comma-separated related models to include
        schema:
          type: string
        in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ./models/PaginatedHostsList.v1.yaml
              examples:
                default:
                  value:
                    hosts:
                    - id: 71
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    - id: 2
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    pagination:
                      total_records: 14
                      current_offset: 41
                      next_offset: 85
          description: Successful response - returns an array of `Host` entities.
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: A generic error
        '401':
          description: You don't have permission to view these Hosts
        '403':
          description: You do not have permission for this action
      operationId: getHosts
      summary: List all Hosts
      description: Gets a list of all `Host` entities.
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/HostCreateParams.v1.yaml
            examples:
              default:
                value:
                  email: some text
                  first_name: some text
                  last_name: some text
                  profile_pic_url: some text
                  department: some text
                  mobile_number: some text
        required: true
      tags:
      - Hosts
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: ./models/Host.v1.yaml
              examples:
                default:
                  value:
                    id: 1
                    email: some text
                    first_name: some text
                    last_name: some text
                    profile_pic_url: some text
                    department: some text
                    mobile_number: some text
          description: Successful response
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
      operationId: createHost
      summary: Create a Host
      description: Creates a Host
  /hosts/batch:
    post:
      summary: Create multiple Hosts
      operationId: createHosts
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: ./models/BatchJob.v1.yaml
              examples:
                default:
                  value:
                    bid: string
                    created_at: date-string
                    status: string
                    total_records: 12
                    worker_name: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
      tags:
      - Hosts
      description: Creates a batch of `Host` records in an async queue. Please note, every action taken against this endpoint is recorded in the audit log.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/HostBatchCreateParams.v1.yaml
            examples: {}
        description: ''
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
components:
  parameters:
    idempotencyKey:
      name: Idempotency-Key
      description: An optional idempotency key to allow for repeat API requests. Any API request with this key will only be executed once, no matter how many times it's submitted. We store idempotency keys for only 24 hours. Any `Idempotency-Key` shorter than 10 characters will be ignored
      schema:
        type: string
      in: header
      required: false
  securitySchemes:
    TractionGuestAuth:
      openIdConnectUrl: https://us.tractionguest.com/.well-known/openid-configuration
      type: openIdConnect
