openapi: 3.2.0
info:
  title: Sign In Solutions VMS Locations API
  version: 0.21.0
  x-logo:
    url: https://signinenterprise.com/wp-content/uploads/tg-logo-light@2.png
    backgroundColor: '#FFFFFF'
    altText: Sign In Solutions
    href: https://signinsolutions.com/signinenterprise
  description: The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.
  contact:
    name: API Support
    url: https://signinsolutions.com/signinenterprise
    email: support@tractionguest.com
servers:
- url: '{domain}'
  variables:
    domain:
      enum:
      - https://us.tractionguest.com/api/v3
      - http://localhost:3000/api/v3
      default: https://us.tractionguest.com/api/v3
security:
- TractionGuestAuth:
  - all
  - openid
  - admin:webhooks
  - watchlists:*
  - watchlists:read
  - watchlists:write
  - users:*
  - users:read
  - users:write
  - visitors:*
  - visitors:read
  - visitors:write
  - parking:*
  - parking:read
  - parking:write
  - locations:*
  - locations:read
  - locations:write
  - hosts:*
  - hosts:read
  - hosts:write
  - email_templates:*
  - email_templates:read
  - email_templates:write
tags:
- name: Locations
  description: All endpoints relating to the Location model, aka. DeviceConfigurations
paths:
  /locations:
    summary: Path used to manage the list of Locations.
    description: The REST endpoint/path used to list zero or more `Location` entities.
    get:
      tags:
      - Locations
      parameters:
      - name: limit
        description: Limits the results to a specified number, defaults to 50
        schema:
          type: integer
        in: query
      - name: offset
        description: Offsets the results to a specified number, defaults to 0
        schema:
          type: integer
        in: query
      - name: query
        description: Queries by Location `name`
        schema:
          type: string
        in: query
      - name: include
        description: A list of comma-separated related models to include
        schema:
          type: string
        in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ./models/PaginatedLocationsList.v1.yaml
              examples:
                default:
                  value:
                    pagination:
                      total_records: 61
                      current_offset: 41
                      next_offset: 28
                    locations:
                    - id: 28
                      name: Default
                      max_capacity: 40
                    - id: 97
                      name: Rogers Arena
                      max_capacity: 45
          description: Successful response - returns an array of `Location` entities.
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: A generic error
        '401':
          description: You don't have permission to view these Locations
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
        '403':
          description: You do not have permission for this action
      operationId: getLocations
      summary: List all Locations
      description: Gets a list of all `Location` entities.
  /locations/{location_id}:
    parameters:
    - schema:
        type: string
      name: location_id
      in: path
      required: true
    get:
      summary: Get the details of a location
      tags:
      - Locations
      responses:
        '200':
          description: Successful response - returns a single `Location`.
          content:
            application/json:
              schema:
                $ref: ./models/Location.v1.yaml
              examples:
                default:
                  value:
                    id: 1
                    name: Default
                    max_capacity: 30
                    timezone: America/Vancouver
        '400':
          description: A generic error
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples: {}
        '401':
          description: You don't have permission to view this Location
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
        '403':
          description: You do not have permission for this action
        '404':
          description: The Location does not exist
      operationId: getLocation
      description: Gets details of a single instance of `Location`.
components:
  securitySchemes:
    TractionGuestAuth:
      openIdConnectUrl: https://us.tractionguest.com/.well-known/openid-configuration
      type: openIdConnect
