openapi: 3.0.2
info:
  title: Sign In Solutions VMS AuditLogs Invites API
  version: 0.21.0
  x-logo:
    url: https://signinenterprise.com/wp-content/uploads/tg-logo-light@2.png
    backgroundColor: '#FFFFFF'
    altText: Sign In Solutions
    href: https://signinsolutions.com/signinenterprise
  description: 'The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.


    # Getting Started

    If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).


    We will also add you to our Slack channel where you can ask questions and get further help.


    # Terms and Conditions

    Please visit: [https://signinsolutions.com/compliance-hub](https://signinsolutions.com/compliance-hub)


    # Versioning

    This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.


    * The `Major` number increments when potentially incompatible changes are made.

    * The `Minor` number increments when backwards-compatible additions are made.

    * The `Patch` number increments when backwards-compatible bug-fixes are made.

    '
  contact:
    name: API Support
    url: https://signinsolutions.com/signinenterprise
    email: support@tractionguest.com
servers:
- url: '{domain}'
  variables:
    domain:
      enum:
      - https://us.tractionguest.com/api/v3
      - http://localhost:3000/api/v3
      default: https://us.tractionguest.com/api/v3
security:
- TractionGuestAuth:
  - all
  - openid
  - admin:webhooks
  - watchlists:*
  - watchlists:read
  - watchlists:write
  - users:*
  - users:read
  - users:write
  - visitors:*
  - visitors:read
  - visitors:write
  - parking:*
  - parking:read
  - parking:write
  - locations:*
  - locations:read
  - locations:write
  - hosts:*
  - hosts:read
  - hosts:write
  - email_templates:*
  - email_templates:read
  - email_templates:write
tags:
- name: Invites
  description: All endpoints relating to the Invite model
paths:
  /locations/{location_id}/invites:
    summary: Path used to manage a single Location's invites.
    description: The REST endpoint/path used to create single instances of an `Invite` for a specific `Location`.
    parameters:
    - schema:
        type: string
      name: location_id
      in: path
      required: true
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/InviteCreateParams.v1.yaml
            examples:
              default:
                value:
                  company: some text
                  email: some text
                  end_date: '2020-07-17T01:59:59.999Z'
                  last_name: some text
                  start_date: '2020-07-17T01:59:59.999Z'
                  title: some text
                  watchlist_colour: ORANGE
                  host_ids:
                  - 96
                  - 2
                  flex_values:
                  - flex_definition_id: 1
                    raw_value: Canada
                    label: Country
                  - flex_definition_id: 2
                    raw_value: English
                    label: Language
                  email_template_id: 53
                  mobile_number: some text
                  first_name: some text
                  license_plate: some text
                  notification_triggers:
                  - offset_direction: BEFORE
                    offset_unit: days
                    offset_amount: 34
                    offset_origin: START
                    email_template_id: 63
                    notification_groups:
                    - some text
                    - some text
                  - offset_direction: AFTER
                    offset_unit: hours
                    offset_amount: 12
                    offset_origin: END
                    email_template_id: 2
                    notification_groups:
                    - some text
                    - some text
                  parking_stall:
                    stall_number: 66
                    parking_lot_id: 321
                    parking_stall_id: 332
        required: true
      tags:
      - Invites
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: ./models/InviteDetail.v1.yaml
              examples:
                default:
                  value:
                    id: 93
                    company: some text
                    created_at: '2020-07-17T01:59:59.999Z'
                    email: some text
                    end_date: '2020-07-17T01:59:59.999Z'
                    first_name: some text
                    last_name: some text
                    license_plate: some text
                    start_date: '2020-07-17T01:59:59.999Z'
                    hosts:
                    - id: 23
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    - id: 33
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    location:
                      id: 20
                      name: some text
                    watchlist_colour: YELLOW
                    email_template:
                      id: 15
                      name: some text
                      template_type: some text
                    custom_fields:
                    - format: string
                      field_name: some text
                      field_value: some text
                    - format: string
                      field_name: some text
                      field_value: some text
                    notification_triggers:
                    - offset_direction: AFTER
                      offset_amount: 66
                      offset_origin: END
                      email_template_id: 80
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: hours
                      email_template_name: some text
                    - offset_direction: BEFORE
                      offset_amount: 21
                      offset_origin: END
                      email_template_id: 30
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: days
                      email_template_name: some text
                    mobile_number: some text
                    invite_watchlist:
                      id: 3
                      external_colours:
                      - some text
                      internal_colours:
                      - some text
                      - some text
          description: Created the `Invite` for the `Location`
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: A generic error
        '401':
          description: You don't have permission to create this Invite
        '403':
          description: You do not have permission for this action
        '404':
          description: The Location does not exist
        '422':
          description: Your request was not formatted correctly
      operationId: createLocationInvite
      summary: Create an Invite
      description: Creates a new `Invite` for a specific `Location`.
  /invites:
    summary: Path used to manage the list of Invites.
    description: The REST endpoint/path used to list and create zero or more `Invite` entities.  This path contains a `GET` and `POST` operation to perform the list and create tasks, respectively.
    get:
      tags:
      - Invites
      parameters:
      - name: limit
        description: Limits the results to a specified number, defaults to 50
        schema:
          type: integer
        in: query
      - name: offset
        description: Offsets the results to a specified number, defaults to 0
        schema:
          type: integer
        in: query
      - name: query
        description: Filters by `first_name`, `last_name`, `company`, and `email`
        schema:
          type: string
        in: query
      - name: with_colours
        description: 'A comma separated list of case-insensitive colour values.

          i.e., `red`, `green`, `yellow`, and `orange`'
        schema:
          type: string
        in: query
      - name: location_ids
        description: A comma separated list of Location IDs
        schema:
          type: string
        in: query
      - name: sort_by
        description: Sorts by the field name and direction provided where the pattern is `FIELD_NAME_DIRECTION`
        schema:
          enum:
          - start_date_asc
          - start_date_desc
          - end_date_asc
          - end_date_desc
          - created_at_asc
          - created_at_desc
          - updated_at_asc
          - updated_at_desc
        in: query
      - name: starts_before
        description: Filters results to all those *before* the provided datetime
        schema:
          format: date
          type: string
        in: query
      - name: starts_after
        description: Filters results to all those *after* the provided datetime
        schema:
          format: date
          type: string
        in: query
      - name: include
        description: 'A list of comma-separated related models to include

          i.e., ''assigned_stall'''
        schema:
          type: string
        in: query
      - name: is_approved
        description: True to return approved and auto approved invites, False to return pending and rejected invites
        schema:
          type: boolean
        in: query
      - name: active_after
        description: Checks that an invite hasn't yet started, or has started and is still active after a specified time
        schema:
          format: date-time
          type: string
        in: query
      - name: active_before
        description: Checks that an invite hasn't ended before a specified time
        schema:
          format: date-time
          type: string
        in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ./models/PaginatedInvitesList.v1.yaml
              examples:
                default:
                  value:
                    pagination:
                      total_records: 89
                      current_offset: 72
                      next_offset: 29
                      last_id: 49
                    invites:
                    - id: 37
                      first_name: some text
                      last_name: some text
                      start_date: '2018-02-10T09:30:00Z'
                      location:
                        id: 70
                        name: some text
                      watchlist_colour: RED
                      hosts:
                      - id: 78
                        email: some text
                        first_name: some text
                        last_name: some text
                        profile_pic_url: some text
                        department: some text
                        mobile_number: some text
                      - id: 41
                        email: some text
                        first_name: some text
                        last_name: some text
                        profile_pic_url: some text
                        department: some text
                        mobile_number: some text
                      invite_watchlist:
                        id: 61
                        external_colours:
                        - some text
                        - some text
                        internal_colours:
                        - some text
                        - some text
                        external:
                        - search_terms:
                            name: some text
                            company: some text
                            city: some text
                            country: some text
                            state: some text
                          integration: some text
                          colour: YELLOW
                          matches:
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                        - search_terms:
                            name: some text
                            company: some text
                            city: some text
                            country: some text
                            state: some text
                          integration: some text
                          colour: RED
                          matches:
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                        internal:
                        - id: 92
                          email: some text
                          colour: some text
                          last_name: some text
                          first_name: some text
                        - id: 44
                          email: some text
                          colour: some text
                          last_name: some text
                          first_name: some text
                      end_date: '2020-07-17T01:59:59.999Z'
                      email: some text
                      mobile_number: some text
                    - id: 0
                      first_name: some text
                      last_name: some text
                      start_date: '2018-02-10T09:30:00Z'
                      location:
                        id: 66
                        name: some text
                      watchlist_colour: RED
                      hosts:
                      - id: 92
                        email: some text
                        first_name: some text
                        last_name: some text
                        profile_pic_url: some text
                        department: some text
                        mobile_number: some text
                      - id: 85
                        email: some text
                        first_name: some text
                        last_name: some text
                        profile_pic_url: some text
                        department: some text
                        mobile_number: some text
                      invite_watchlist:
                        id: 57
                        external_colours:
                        - some text
                        - some text
                        internal_colours:
                        - some text
                        - some text
                        external:
                        - search_terms:
                            name: some text
                            company: some text
                            city: some text
                            country: some text
                            state: some text
                          integration: some text
                          colour: GREEN
                          matches:
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                        - search_terms:
                            name: some text
                            company: some text
                            city: some text
                            country: some text
                            state: some text
                          integration: some text
                          colour: YELLOW
                          matches:
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                          - id: some text
                            alt_names:
                            - some text
                            - some text
                            federal_register_notice: some text
                            name: some text
                            source_information_url: some text
                            source_list_url: some text
                            list: some text
                            type: some text
                            category: some text
                            street1: some text
                            street2: some text
                            city: some text
                            state: some text
                            country: some text
                            notes: some text
                            frc: some text
                            start: some text
                            end: some text
                            frserve: some text
                            optional_ID: some text
                            alert_type: some text
                            pair_status: some text
                            pair_reason: some text
                            pair_comments: some text
                            application_display_name: some text
                            application_id: some text
                            client_id: some text
                            client_key: some text
                            client_full_name: some text
                            list_key: some text
                            list_name: some text
                            list_id: some text
                            list_version: some text
                            list_modify_date: some text
                            list_profile_id: some text
                            list_profile_key: some text
                            link_single_string_name: some text
                            list_parent_single_string_name: some text
                            list_category: some text
                            list_pep_category: some text
                            list_do_bs: some text
                            list_countries: some text
                            rank_string: some text
                            ranktype: some text
                            rankweight: some text
                            pair_load_date: some text
                            e_address_to: some text
                            e_address_cc: some text
                            origin: some text
                            secondsviewed: some text
                            initial_user: some text
                            is_pair_parent_flag: some text
                            pair_met_search_criteria_flag: some text
                            editable_due_to_assignment_flag: some text
                            modify_date: some text
                            modified_by_user: some text
                            pair_report_type: some text
                            finscan_category: some text
                            wrapper_status: some text
                            source_lists: some text
                        internal:
                        - id: 46
                          email: some text
                          colour: some text
                          last_name: some text
                          first_name: some text
                        - id: 37
                          email: some text
                          colour: some text
                          last_name: some text
                          first_name: some text
                      end_date: '2020-07-17T01:59:59.999Z'
                      email: some text
                      mobile_number: some text
          description: Successful response - returns an array of `Invite` entities.
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: A generic error
        '401':
          description: You don't have permission to view these Invites
        '403':
          description: You do not have permission for this action
      operationId: getInvites
      summary: List all Invites
      description: Gets a list of all `Invite` entities.
  /invites/batch_delete:
    post:
      summary: Delete Multiple Invites
      tags:
      - Invites
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: ./models/BatchJob.v1.yaml
        4XX:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
      operationId: batchDeleteInvites
      description: Queues up a "delete" background task for one or more `Invite` entities.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/IdentifierList.v1.yaml
        description: ''
  /registrations/{registration_id}/invites:
    summary: Path used to create an `Invite` from `Registration` data.
    description: The REST endpoint/path used to create an instance of an `Invite`. This path contains a `POST` operation used to perform the create task.
    parameters:
    - schema:
        type: string
      name: registration_id
      in: path
      required: true
    post:
      tags:
      - Invites
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: ./models/InviteDetail.v1.yaml
              examples:
                default:
                  value:
                    id: 93
                    company: some text
                    created_at: '2020-07-17T01:59:59.999Z'
                    email: some text
                    end_date: '2020-07-17T01:59:59.999Z'
                    first_name: some text
                    last_name: some text
                    start_date: '2020-07-17T01:59:59.999Z'
                    hosts:
                    - id: 23
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    - id: 33
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    location:
                      id: 20
                      name: some text
                    watchlist_colour: YELLOW
                    email_template:
                      id: 15
                      name: some text
                      template_type: some text
                    custom_fields:
                    - format: string
                      field_name: some text
                      field_value: some text
                    - format: string
                      field_name: some text
                      field_value: some text
                    notification_triggers:
                    - offset_direction: AFTER
                      offset_amount: 66
                      offset_origin: END
                      email_template_id: 80
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: hours
                      email_template_name: some text
                    - offset_direction: BEFORE
                      offset_amount: 21
                      offset_origin: END
                      email_template_id: 30
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: days
                      email_template_name: some text
                    mobile_number: some text
                    invite_watchlist:
                      id: 3
                      external_colours:
                      - some text
                      internal_colours:
                      - some text
                      - some text
          description: Created an `Invite` from the given `Registration` UUID.
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: A generic error
        '401':
          description: You don't have permission to create this Invite
        '403':
          description: You do not have permission for this action
        '404':
          description: The Location does not exist
        '422':
          description: Your request was not formatted correctly
      operationId: createRegistrationInvite
      summary: Create an Invite from a Registration
      description: Creates a new `Invite` from `Registration` data.
  /invites/{invite_id}:
    summary: Path used to manage a single Invite.
    description: The REST endpoint/path used to get, update, and delete single instances of an `Invite`.  This path contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and delete tasks, respectively.
    parameters:
    - schema:
        type: string
      name: invite_id
      in: path
      required: true
    get:
      tags:
      - Invites
      parameters:
      - name: include
        description: 'A list of comma-separated related models to include

          i.e., ''assigned_stall'''
        schema:
          type: string
        in: query
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: ./models/InviteDetail.v1.yaml
              examples:
                default:
                  value:
                    id: 2
                    company: some text
                    created_at: '2020-07-17T01:59:59.999Z'
                    email: some text
                    end_date: '2020-07-17T01:59:59.999Z'
                    first_name: some text
                    last_name: some text
                    start_date: '2020-07-17T01:59:59.999Z'
                    hosts:
                    - id: 68
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    - id: 82
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    location:
                      id: 10
                      name: some text
                    watchlist_colour: GREEN
                    email_template:
                      id: 0
                      name: some text
                      template_type: some text
                    custom_fields:
                    - format: string
                      field_name: some text
                      field_value: some text
                    - format: string
                      field_name: some text
                      field_value: some text
                    notification_triggers:
                    - offset_direction: AFTER
                      offset_amount: 95
                      offset_origin: START
                      email_template_id: 83
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: days
                      email_template_name: some text
                    - offset_direction: AFTER
                      offset_amount: 32
                      offset_origin: END
                      email_template_id: 32
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: days
                      email_template_name: some text
                    mobile_number: some text
                    invite_watchlist:
                      id: 47
                      external_colours:
                      - some text
                      - some text
                      internal_colours:
                      - some text
                      - some text
          description: Successful response - returns a single `Invite`.
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: A generic error
        '401':
          description: You don't have permission to view this Invite
        '403':
          description: You do not have permission for this action
        '404':
          description: The Invite you are looking for does not exist
      operationId: getInvite
      summary: Get an Invite
      description: Gets the details of a single instance of a `Invite`.
    put:
      requestBody:
        description: Updated `Invite` information.
        content:
          application/json:
            schema:
              $ref: ./models/InviteUpdateParams.v1.yaml
            examples:
              default:
                value:
                  on_premise: true
                  user_id: 45
                  license_plate: some text
                  flex_values:
                  - flex_definition_id: 1
                    raw_value: Canada
                    label: Country
                  - flex_definition_id: 2
                    raw_value: English
                    label: Language
        required: true
      tags:
      - Invites
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: ./models/InviteDetail.v1.yaml
              examples:
                default:
                  value:
                    id: 54
                    company: some text
                    created_at: '2020-07-17T01:59:59.999Z'
                    email: some text
                    end_date: '2020-07-17T01:59:59.999Z'
                    first_name: some text
                    last_name: some text
                    license_plate: some text
                    start_date: '2020-07-17T01:59:59.999Z'
                    hosts:
                    - id: 64
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    - id: 54
                      email: some text
                      first_name: some text
                      last_name: some text
                      mobile_number: some text
                      profile_pic_url: some text
                    location:
                      id: 67
                      name: some text
                    watchlist_colour: YELLOW
                    email_template:
                      id: 77
                      name: some text
                      template_type: some text
                    custom_fields:
                    - format: string
                      field_name: some text
                      field_value: some text
                    - format: string
                      field_name: some text
                      field_value: some text
                    notification_triggers:
                    - offset_direction: AFTER
                      offset_amount: 45
                      offset_origin: START
                      email_template_id: 93
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: hours
                      email_template_name: some text
                    - offset_direction: AFTER
                      offset_amount: 28
                      offset_origin: END
                      email_template_id: 19
                      notification_groups:
                      - some text
                      - some text
                      offset_unit: days
                      email_template_name: some text
                    mobile_number: some text
                    invite_watchlist:
                      id: 43
                      external_colours:
                      - some text
                      internal_colours:
                      - some text
          description: Successful response.
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: A generic error
        '401':
          description: You don't have permission to view this Invite
        '403':
          description: You do not have permission for this action
        '404':
          description: The Invite does not exist
        '422':
          description: Your request was not formatted correctly
      operationId: updateInvite
      summary: Update an Invite
      description: Updates an existing `Invite`.
    delete:
      tags:
      - Invites
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      responses:
        '204':
          description: The `Invite` has been deleted
        '400':
          content:
            application/json:
              schema:
                $ref: ./models/ErrorsList.v1.yaml
              examples:
                default:
                  value:
                    errors:
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
                    - domain: some text
                      attribute: some text
                      code: some text
                      message: some text
          description: There was an error in trying to delete the `Invite`
      operationId: deleteInvite
      summary: Deletes an Invite
      description: Deletes a single instance of `Invite`
components:
  parameters:
    idempotencyKey:
      name: Idempotency-Key
      description: An optional idempotency key to allow for repeat API requests. Any API request with this key will only be executed once, no matter how many times it's submitted. We store idempotency keys for only 24 hours. Any `Idempotency-Key` shorter than 10 characters will be ignored
      schema:
        type: string
      in: header
      required: false
  securitySchemes:
    TractionGuestAuth:
      openIdConnectUrl: https://us.tractionguest.com/.well-known/openid-configuration
      type: openIdConnect
